[build]
  functions = "netlify/functions"

# Pretty API path
[[redirects]]
  from = "/api/share"
  to   = "/.netlify/functions/share"
  status = 200
  force  = true

# Shortlinks:
# Visiting https://<your-netlify-site>/s/AB12cd34 will 301-redirect users
# to your Squarespace app with ?id=AB12cd34
[[redirects]]
  from = "/s/:id"
  to   = "https://www.worldstoneonline.com/cad-lite?id=:id"
  status = 301
  force  = true
