[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/share"
  to   = "/.netlify/functions/share"
  status = 200
  force  = true

# Shortlinks to Squarespace with ?id=
[[redirects]]
  from = "/s/:id"
  to   = "https://www.worldstoneonline.com/cad-lite?id=:id"
  status = 301
  force  = true
